# Generated by Django 4.2.7 on 2023-12-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafeinformation", "0002_csvfilecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cafe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cafe_class", models.CharField(max_length=255)),
                ("review_count", models.IntegerField()),
                ("address", models.CharField(max_length=255)),
                ("review_top3", models.TextField()),
                ("background_image_url", models.URLField()),
                ("cafe_menu", models.TextField()),
            ],
        ),
    ]
