# Generated by Django 4.2.7 on 2023-12-01 00:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafeinformation", "0003_cafe"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cafe",
            new_name="GangNamCafe",
        ),
    ]
