# Generated by Django 4.2.7 on 2023-12-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafeinformation", "0004_rename_cafe_gangnamcafe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gangnamcafe",
            name="review_count",
            field=models.CharField(max_length=255),
        ),
    ]
