# Generated by Django 4.2.7 on 2023-12-01 00:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafeinformation", "0005_alter_gangnamcafe_review_count"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GangNamCafe",
        ),
    ]
