# Generated by Django 4.2.7 on 2023-12-08 00:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafeinformation", "0011_delete_gangnamcafe"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CsvFilecontent",
        ),
    ]
