# Generated by Django 4.2.7 on 2023-11-22 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gamename", models.CharField(max_length=50)),
                ("opponent_name", models.CharField(max_length=20)),
                ("opponent_date", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schoolname", models.CharField(max_length=50)),
                ("grade", models.CharField(max_length=50)),
                ("playername", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("pitchingtype", models.CharField(max_length=20)),
                ("intro", models.TextField(max_length=2000)),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record", models.CharField(default="", max_length=100)),
                ("position", models.CharField(default="", max_length=100)),
                ("speed", models.IntegerField(default=135)),
                ("ballcourse", models.CharField(default="", max_length=2)),
                (
                    "opponent_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="player_info.opponent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="opponent",
            name="playerinfo_reference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="player_info.playerinfo"
            ),
        ),
        migrations.CreateModel(
            name="BallData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_pitches", models.IntegerField(default=0)),
                ("total_fast_ball", models.IntegerField(default=0)),
                ("total_breaking_ball", models.IntegerField(default=0)),
                ("total_speed_off_ball", models.IntegerField(default=0)),
                ("foursim_ball", models.IntegerField(default=0)),
                ("twosim_ball", models.IntegerField(default=0)),
                ("cutfast_ball", models.IntegerField(default=0)),
                ("curve_ball", models.IntegerField(default=0)),
                ("slider_ball", models.IntegerField(default=0)),
                ("sinker_ball", models.IntegerField(default=0)),
                ("circlechan_ball", models.IntegerField(default=0)),
                ("splitter_ball", models.IntegerField(default=0)),
                ("fork_ball", models.IntegerField(default=0)),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="player_info.opponent",
                    ),
                ),
            ],
        ),
    ]
