# Generated by Django 4.2.7 on 2023-12-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_info", "0002_balldata_left_hitter_total_breaking_ball_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="ballcourse",
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
