# Generated by Django 4.2.7 on 2023-12-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_info", "0012_alter_opponent_opponent_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="hitter_num",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="record",
            name="strike_ball",
            field=models.CharField(default="", max_length=10),
        ),
    ]
