# Generated by Django 4.2.7 on 2023-12-01 05:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafeinformation", "0010_seoulcafelist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GangNamCafe",
        ),
    ]
